/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece568.erss.amazon;

import edu.duke.ece568.erss.amazon.WorldAmazonProtocol.ACommands;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        ACommands.Builder acommand = ACommands.newBuilder();

        acommand.mergeFrom(new FileInputStream("./test.txt"));
        System.out.println(acommand.getAcks(0));
        System.out.println(acommand.getAcksCount());
        System.out.println(acommand.getSimspeed());

        acommand.addAcks(1);
        acommand.setSimspeed(10);

        FileOutputStream out = new FileOutputStream("./test.txt");
        acommand.build().writeTo(out);
        out.close();
    }
}
