version: '2'

services:
  db:
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: amazon
      restart: always
      volumes:
        - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./web-app
      command: bash -c "./wait-for-it.sh db:5432 --strict -- ./initserver.sh"
      volumes:
        - ./web-app:/code
      depends_on:
        - db
  web:
      build: ./web-app
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./web-app:/code
      expose:
        - "8000"
      depends_on:
        - web-init
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - web
  # daemon should run after the front-end has setted up(since we need the data from it, e.g. warehouse)
  daemon:
    build: ./daemon
    command: bash -c "./gradlew run"
    ports:
      - "9999:9999" # port for UPS
      - "8888:8888" # port for web
    depends_on:
      - web
volumes:
   data-volume: 
