# Generated by Django 3.0.5 on 2020-04-10 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.IntegerField(default=1)),
                ('status', models.CharField(default='processing', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('item', models.OneToOneField(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='item', to='amazon.Item')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.Package')),
            ],
        ),
    ]
